// <auto-generated />
using System;
using GroundControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroundControl.Api.Data.Migrations
{
    [DbContext(typeof(GroundDbContext))]
    partial class GroundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroundControl.Api.Data.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("GroundControl.Api.Models.EdgeEntity", b =>
                {
                    b.Property<string>("EdgeId")
                        .HasColumnType("text")
                        .HasColumnName("edge_id");

                    b.Property<string>("FromNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_node");

                    b.Property<double>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<string>("ToNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_node");

                    b.HasKey("EdgeId");

                    b.ToTable("edges", (string)null);
                });

            modelBuilder.Entity("GroundControl.Api.Models.EdgeOccupancy", b =>
                {
                    b.Property<string>("EdgeId")
                        .HasColumnType("text")
                        .HasColumnName("edge_id");

                    b.Property<string>("OccupiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occupied_by");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EdgeId");

                    b.ToTable("edge_occupancy", (string)null);
                });

            modelBuilder.Entity("GroundControl.Api.Models.NodeEntity", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeType")
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("NodeId");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("GroundControl.Api.Models.RouteEntity", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgesPathJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edges_path_json");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FromNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_node");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_node");

                    b.Property<int>("TtlRemainingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("ttl_remaining_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("RouteId");

                    b.ToTable("routes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
