// <auto-generated />
using System;
using GroundControl.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroundControl.Infrastructure.Migrations
{
    [DbContext(typeof(GroundControlDbContext))]
    [Migration("20260307004316_AddTtlRemainingMinutes")]
    partial class AddTtlRemainingMinutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroundControl.Core.Models.Edge", b =>
                {
                    b.Property<string>("EdgeId")
                        .HasColumnType("text")
                        .HasColumnName("edge_id");

                    b.Property<string>("FromNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_node");

                    b.Property<decimal>("Length")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(1m)
                        .HasColumnName("length");

                    b.Property<string>("ToNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_node");

                    b.HasKey("EdgeId");

                    b.HasIndex("FromNode")
                        .HasDatabaseName("edges_from_idx");

                    b.HasIndex("ToNode")
                        .HasDatabaseName("edges_to_idx");

                    b.ToTable("edges", (string)null);
                });

            modelBuilder.Entity("GroundControl.Core.Models.EdgeOccupancy", b =>
                {
                    b.Property<string>("EdgeId")
                        .HasColumnType("text")
                        .HasColumnName("edge_id");

                    b.Property<string>("OccupiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occupied_by");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EdgeId");

                    b.ToTable("edge_occupancy", (string)null);
                });

            modelBuilder.Entity("GroundControl.Core.Models.Node", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeType")
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric")
                        .HasColumnName("y");

                    b.HasKey("NodeId");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("GroundControl.Core.Models.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EventId");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("GroundControl.Core.Models.Route", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EdgesPath")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("edges_path");

                    b.Property<string>("FromNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_node");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_node");

                    b.Property<int>("TtlRemainingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("ttl_remaining_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("RouteId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("routes_vehicle_idx");

                    b.ToTable("routes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
